# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemindAt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'remindmelatr_remindat',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, b'Paused'), (2, b'Live'), (3, b'Snoozed'), (4, b'Overdue'), (5, b'Completed'), (6, b'Cancelled'), (7, b'Deleted')], default=2)),
                ('content', models.TextField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('interval_type', models.IntegerField(choices=[(1, b'Minutes'), (2, b'Hours'), (3, b'Days'), (4, b'Months'), (5, b'Years')], null=True)),
                ('interval_value', models.IntegerField(null=True)),
                ('max_recurrances', models.IntegerField(default=0)),
                ('scheduled_end_date', models.DateTimeField(null=True)),
                ('completion_date', models.DateTimeField(null=True)),
                ('snooze_count', models.IntegerField(default=0)),
                ('snooze_timeout_value', models.IntegerField(default=1)),
                ('snooze_timeout_interval', models.IntegerField(choices=[(1, b'Minutes'), (2, b'Hours'), (3, b'Days'), (4, b'Months'), (5, b'Years')], default=2)),
                ('hash_digest', models.CharField(max_length=150, unique=True)),
                ('next_fire', models.DateTimeField(null=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('total_reminders', models.IntegerField(default=0)),
                ('total_snoozes', models.IntegerField(default=0)),
                ('full_start_datetime', models.DateTimeField()),
                ('desktop_notification_sent', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('full_start_datetime',),
                'db_table': 'remindmelatr_reminder',
            },
        ),
        migrations.CreateModel(
            name='ReminderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('internal', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(1, b'Paused'), (2, b'Live'), (3, b'Snoozed'), (4, b'Overdue'), (5, b'Completed'), (6, b'Cancelled'), (7, b'Deleted')])),
                ('content', models.TextField()),
                ('snooze_count', models.IntegerField(default=0)),
                ('total_reminders', models.IntegerField(default=0)),
                ('total_snoozes', models.IntegerField(default=0)),
                ('full_start_datetime', models.DateTimeField()),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.Reminder')),
            ],
            options={
                'ordering': ('-created',),
                'db_table': 'remindmelatr_reminderhistory',
            },
        ),
        migrations.CreateModel(
            name='RemindOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'remindmelatr_remindon',
            },
        ),
    ]
